### ISSUE TITLE
[BUG]: Plugin not reporting 

### ISSUE THREAD

**Issue by chris-m92** [dipakparmar/docusaurus-plugin-umami#54] opened 2024-05-22 03:10 UTC
### Description of the bug

When deploying my docusaurus site and then visiting, it does not show up any page views in Realtime, nor track events.

### Steps To Reproduce

Docusaurus Version: 3.3.2
Plugin Version: 2.1.5

In my `docusaurus.config.ts` file I have the following:

```
themeConfig: {
  ...
    plugins: [
      [
        '@dipakparmar/docusaurus-plugin-umami',
        {
          websiteID: '<MY-WEBSITE-ID>',
          analyticsDomain: 'umami.my-domain.com',
          dataAutoTrack: true,
        },
      ],
    ],
 ...
}
```

However, once built and deployed, I do not see any `<script>` tags in `<head>` attempting to download the script.js nor in network requests and beyond that, no data shows up in my umami dashboard.

**Comment by dipakparmar** [comment] 2024-05-22 03:33
@chris-m92 The plugin is disabled by default in the development environment to prevent polluting the analytics data. Have you tried running it in the production environment?

Also, if you see the issue in production as well, can you try any previous versions to confirm whether it's specific to this version?

**Comment by chris-m92** [comment] 2024-05-22 03:42
Yes I did build it and deploy to the live site and it still did not work.

I ended up using the config `headTags` to accomplish this, however.

**Comment by dipakparmar** [comment] 2024-05-22 03:43
@chris-m92  is the code publicly available that i can test?

**Comment by dipakparmar** [comment] 2024-05-22 03:53
@chris-m92 also check [my site](https://docs.dipak.tech/), i just deployed the latest version, i don't see the same with it.

**Comment by chris-m92** [comment] 2024-05-22 03:56
That's weird, I'll try again tomorrow.

**Comment by chris-m92** [comment] 2024-05-22 22:11
@dipakparmar This is super low priority,  btw, again I moved to just using the `headTags` in my `docusaurus.config.ts` file to accomplish the same thing. 

However, I noticed that in your deployment of your docs diary, the plugin uses `require.resolve('@dipakparmar/docusaurus-plugin-umami')` vs. just a string to identify the plugin. I can test but maybe that is the issue.

**Comment by dipakparmar** [comment] 2024-05-25 17:25
> @dipakparmar This is super low priority, btw, again I moved to just using the `headTags` in my `docusaurus.config.ts` file to accomplish the same thing.
> 
> However, I noticed that in your deployment of your docs diary, the plugin uses `require.resolve('@dipakparmar/docusaurus-plugin-umami')` vs. just a string to identify the plugin. I can test but maybe that is the issue.

That should not be an issue, but it's better to be safe to use resolve as my plugin is not directly in the root of Docusaurus. However, Node.js somehow figures it out without and still works.

I would suggest if you can share codesandbox version where I can troubleshoot if this is something I need to fix in plugin.

**Comment by dipakparmar** [comment] 2024-06-08 01:51
I am closing this as I cannot reproduce it or do not have enough info to reproduce it!

**Closed as not planned** 2024-06-08 01:51 UTC
Labels: bug
